package app.suhocki.mybooks.di

object DI {
    const val APP_SCOPE = "APP_SCOPE"
    const val SPLASH_ACTIVITY_SCOPE = "SPLASH_ACTIVITY_SCOPE"
    const val INITIAL_ACTIVITY_SCOPE = "INITIAL_ACTIVITY_SCOPE"
    const val BACKGROUND_SERVICE_SCOPE = "BACKGROUND_SERVICE_SCOPE"
    const val CATALOG_ACTIVITY_SCOPE = "CATALOG_ACTIVITY_SCOPE"
    const val BOOKS_ACTIVITY_SCOPE = "BOOKS_ACTIVITY_SCOPE"
    const val DETAILS_ACTIVITY_SCOPE = "DETAILS_ACTIVITY_SCOPE"
}