package app.suhocki.mybooks.di

object DI {
    const val APP_SCOPE = "APP_SCOPE"
    const val MAIN_ACTIVITY_SCOPE = "MAIN_ACTIVITY_SCOPE"
    const val INITIAL_ACTIVITY_SCOPE = "INITIAL_ACTIVITY_SCOPE"
    const val BACKGROUND_SERVICE_SCOPE = "BACKGROUND_SERVICE_SCOPE"
    const val BOOKS_ACTIVITY_SCOPE = "BOOKS_ACTIVITY_SCOPE"
    const val DETAILS_ACTIVITY_SCOPE = "DETAILS_ACTIVITY_SCOPE"
    const val SEARCH_FILTER_ACTIVITY_SCOPE = "SEARCH_FILTER_ACTIVITY_SCOPE"
    const val LICENSES_ACTIVITY_SCOPE = "LICENSES_ACTIVITY_SCOPE"
    const val CHANGELOG_ACTIVITY_SCOPE = "CHANGELOG_ACTIVITY_SCOPE"
    const val GSON_SCOPE = "GSON_SCOPE"
}